import { Product, Review, CoreValue, Banner } from './types';

export const HERO_BANNERS: Banner[] = [
  { id: '1', image: 'https://picsum.photos/1200/400?random=101', title: 'Công Nghệ Sinh Học - An Toàn Cho Cả Gia Đình' },
  { id: '2', image: 'https://picsum.photos/1200/400?random=102', title: 'D-Bii: Sạch Thơm - Tinh Khiết' },
  { id: '3', image: 'https://picsum.photos/1200/400?random=103', title: 'Giải Pháp Vệ Sinh Nhà Cửa Toàn Diện' },
];

export const SIDE_BANNERS: Banner[] = [
  { id: 's1', image: 'https://picsum.photos/400/195?random=104' },
  { id: 's2', image: 'https://picsum.photos/400/195?random=105' },
];

export const PRODUCTS: Product[] = [
  // --- SINGLE PRODUCTS ---
  {
    id: '1',
    name: 'Tẩy bồn cầu D-Bii (500g)',
    price: 55000,
    originalPrice: 60000,
    image: '/assets/products/dbii_taytoilet.jpg',
    images: ['/assets/products/dbii_taytoilet_2.jpg', '/assets/products/dbii_taytoilet_3.jpg', '/assets/products/dbii_taytoilet_4.jpg', '/assets/products/dbii_taytoilet_5.jpg'],
    category: 'Vệ sinh nhà cửa',
    description: `'Thùng 27 chai. Tẩy sạch siêu nhanh, diệt khuẩn.'`,
    details: '<p>Quy cách: Thùng 27 chai.</p>',
    soldCount: 1250,
  },
  {
    id: '2',
    name: 'Siêu tẩy đa năng D-Bii (500g)',
    price: 95000,
    originalPrice: 150000,
    image: '/assets/products/dbii_taydanang.jpg',
    images: ['/assets/products/dbii_taydanang_2.jpg', '/assets/products/dbii_taydanang_3.jpg', '/assets/products/dbii_taydanang_4.jpg', '/assets/products/dbii_taydanang_5.jpg'],
    category: 'Vệ sinh nhà cửa',
    description: 'Thùng 24 chai. Đánh bay dầu mỡ, rỉ sét.',
    details: '<p>Quy cách: Thùng 24 chai.</p>',
    soldCount: 890,
  },
  {
    id: '3',
    name: 'Nước giặt xả công nghệ sinh học D-bii (1kg)',
    price: 50000,
    originalPrice: 60000,
    image: '/assets/products/dbii_giatxa.jpg',
    images: ['/assets/products/dbii_giatxa_2.jpg', '/assets/products/dbii_giatxa_3.jpg', '/assets/products/dbii_giatxa_4.jpg', '/assets/products/dbii_giatxa_5.jpg'],
    category: 'Giặt giũ',
    description: 'Thùng 6 can. Sạch thơm, mềm vải.',
    details: '<p>Quy cách: Thùng 6 can.</p>',
    soldCount: 3400,
  },
  {
    id: '4',
    name: 'Tinh dầu tỏa hương (270g)',
    price: 79000,
    originalPrice: 95000,
    image: '/assets/products/dbii_tinhdau.jpg',
    images: ['/assets/products/dbii_tinhdau_2.jpg', '/assets/products/dbii_tinhdau_3.jpg', '/assets/products/dbii_tinhdau_4.jpg', '/assets/products/dbii_tinhdau_5.jpg', '/assets/products/dbii_tinhdau_6.jpg', '/assets/products/dbii_tinhdau_7.jpg', '/assets/products/dbii_tinhdau_8.jpg', '/assets/products/dbii_tinhdau_9.jpg'],
    category: 'Khử mùi',
    description: 'Thùng 20 chai. Hương thơm tự nhiên.',
    details: '<p>Quy cách: Thùng 20 chai.</p>',
    soldCount: 560,
  },
  {
    id: '5',
    name: 'Cốc thả bồn cầu D-bii (180g)',
    price: 70000,
    originalPrice: 85000,
    image: '/assets/products/dbii_thaboncau.jpg',
    images: ['/assets/products/dbii_thaboncau_2.jpg', '/assets/products/dbii_thaboncau_3.jpg', '/assets/products/dbii_thaboncau_4.jpg', '/assets/products/dbii_thaboncau_5.jpg'],
    category: 'Vệ sinh nhà cửa',
    tag: 'Bán chạy',
    description: 'Thùng 35 chai. Tự động làm sạch, khử mùi.',
    details: '<p>Quy cách: Thùng 35 chai.</p>',
    soldCount: 5200,
  },
  {
    id: '6',
    name: 'Xả vải công nghệ sinh học D-bii (1kg)',
    price: 60000,
    originalPrice: 65000,
    image: '/assets/products/dbii_xavai.jpg',
    images: ['/assets/products/dbii_xavai_2.jpg', '/assets/products/dbii_xavai_3.jpg', '/assets/products/dbii_xavai_4.jpg', '/assets/products/dbii_xavai_5.jpg', '/assets/products/dbii_xavai_6.jpg', '/assets/products/dbii_xavai_7.jpg', '/assets/products/dbii_xavai_8.jpg', '/assets/products/dbii_xavai_9.jpg'],
    category: 'Giặt giũ',
    description: 'Thùng 6 can. Lưu hương dài lâu.',
    details: '<p>Quy cách: Thùng 6 can.</p>',
    soldCount: 1100,
  },

  // --- PUBLIC COMBOS (c1 - c4) ---
  {
    id: 'c1',
    name: 'Combo 3 chai tẩy Toilet',
    price: 95000,
    originalPrice: 180000,
    image: '/public/assets/products/Combo_C1.jpg',
    images: ['/public/assets/products/dbii_taytoilet.jpg', '/public/assets/products/dbii_taytoilet_2.jpg', '/public/assets/products/dbii_taytoilet_3.jpg', '/public/assets/products/dbii_taytoilet_4.jpg', '/public/assets/products/dbii_taytoilet_5.jpg'],
    category: 'Combo Tiết Kiệm',
    tag: 'Hot Deal',
    description: 'Combo 3 chai tẩy toilet. Tiết kiệm hơn.',
    soldCount: 320,
  },
  {
    id: 'c2',
    name: 'Combo 3 tinh dầu tỏa hương',
    price: 115000,
    originalPrice: 285000,
    image: '/public/assets/products/Combo_C2.jpg',
    images: ['/public/assets/products/dbii_tinhdau.jpg', '/public/assets/products/dbii_tinhdau_2.jpg', '/public/assets/products/dbii_tinhdau_3.jpg', '/public/assets/products/dbii_tinhdau_4.jpg', '/public/assets/products/dbii_tinhdau_5.jpg'],
    category: 'Combo Tiết Kiệm',
    description: 'Combo 3 chai tinh dầu thơm mát.',
    soldCount: 150,
  },
  {
    id: 'c3',
    name: 'Combo 3 cốc thả bồn cầu',
    price: 95000,
    originalPrice: 255000,
    image: '/public/assets/products/Combo_C3.jpg',
    images: ['/public/assets/products/dbii_thaboncau.jpg', '/public/assets/products/dbii_thaboncau_2.jpg', '/public/assets/products/dbii_thaboncau_3.jpg', '/public/assets/products/dbii_thaboncau_4.jpg', '/public/assets/products/dbii_thaboncau_5.jpg'],
    category: 'Combo Tiết Kiệm',
    tag: 'Siêu rẻ',
    description: 'Combo 3 cốc thả bồn cầu tiện lợi.',
    soldCount: 880,
  },
  {
    id: 'c4',
    name: 'Combo 5 tẩy bồn cầu',
    price: 135000,
    originalPrice: 300000,
    image: '/public/assets/products/Combo_C4.jpg',
    images: ['/public/assets/products/dbii_taytoilet.jpg', '/public/assets/products/dbii_taytoilet_2.jpg', '/public/assets/products/dbii_taytoilet_3.jpg', '/public/assets/products/dbii_taytoilet_4.jpg', '/public/assets/products/dbii_taytoilet_5.jpg'],
    category: 'Combo Tiết Kiệm',
    description: 'Mua nhiều giảm sâu. Combo 5 chai.',
    soldCount: 210,
  },

  // --- HIDDEN UP SALE ITEMS (no1 - no10) ---
  // Only accessible via #upsale search
  {
    id: 'no1',
    name: 'Nước giặt xả + toả hương + tẩy Toilet',
    price: 98000,
    originalPrice: 215000,
    image: '/public/assets/products/Combo_No01.jpg',
    images: ['/public/assets/products/dbii_giatxa.jpg', '/public/assets/products/dbii_tinhdau.jpg', '/public/assets/products/dbii_taytoilet.jpg'],
    category: 'Combo Tiết Kiệm',
    tag: 'Up Sale',
    isHidden: false,
    description: 'Combo Up Sale đặc biệt.',
    soldCount: 50,
  },
  {
    id: 'no2',
    name: 'Nước giặt xả + tẩy Toilet + thả bồn cầu',
    price: 96000,
    originalPrice: 205000,
    image: '/public/assets/products/Combo_No02.jpg',
    images: ['/public/assets/products/dbii_giatxa.jpg', '/public/assets/products/dbii_taytoilet.jpg', '/public/assets/products/dbii_thaboncau.jpg'],
    category: 'Combo Tiết Kiệm',
    tag: 'Up Sale',
    isHidden: false,
    description: 'Combo Up Sale đặc biệt.',
    soldCount: 45,
  },
  {
    id: 'no3',
    name: 'Siêu tẩy đa năng + tẩy Toilet + toả hương',
    price: 120000,
    originalPrice: 305000,
    image: '/public/assets/products/Combo_No03.jpg',
    images: ['/public/assets/products/dbii_taydanang.jpg', '/public/assets/products/dbii_taytoilet.jpg', '/public/assets/products/dbii_tinhdau.jpg'],
    category: 'Combo Tiết Kiệm',
    tag: 'Up Sale',
    isHidden: false,
    description: 'Combo Up Sale đặc biệt.',
    soldCount: 60,
  },
  {
    id: 'no4',
    name: 'Siêu tẩy + nước giặt xả + tẩy Toilet',
    price: 130000,
    originalPrice: 270000,
    image: '/public/assets/products/Combo_No04.jpg',
    images: ['/public/assets/products/dbii_taydanang.jpg', '/public/assets/products/dbii_giatxa.jpg', '/public/assets/products/dbii_taytoilet.jpg'],
    category: 'Combo Tiết Kiệm',
    tag: 'Up Sale',
    isHidden: false,
    description: 'Combo Up Sale đặc biệt.',
    soldCount: 30,
  },
  {
    id: 'no5',
    name: 'Siêu tẩy + tẩy Toilet + thả bồn cầu',
    price: 118000,
    originalPrice: 295000,
    image: '/public/assets/products/Combo_No05.jpg',
    images: ['/public/assets/products/dbii_taydanang.jpg', '/public/assets/products/dbii_taytoilet.jpg', '/public/assets/products/dbii_thaboncau.jpg'],
    category: 'Combo Tiết Kiệm',
    tag: 'Up Sale',
    isHidden: false,
    description: 'Combo Up Sale đặc biệt.',
    soldCount: 42,
  },
  {
    id: 'no6',
    name: '4 túi nước giặt xả + 2 túi nước xả',
    price: 170000,
    originalPrice: 370000,
    image: '/public/assets/products/Combo_No06.jpg',
    images: ['/public/assets/products/dbii_giatxa.jpg', '/public/assets/products/dbii_xavai.jpg'],
    category: 'Combo Tiết Kiệm',
    tag: 'Up Sale',
    isHidden: false,
    description: 'Combo Up Sale đặc biệt.',
    soldCount: 120,
  },
  {
    id: 'no7',
    name: '6 túi giặt 1kg (tổng 6kg)',
    price: 165000,
    originalPrice: 360000,
    image: '/public/assets/products/Combo_No07.jpg',
    images: ['/public/assets/products/dbii_giatxa.jpg', '/public/assets/products/dbii_giatxa_2.jpg', '/public/assets/products/dbii_giatxa_3.jpg', '/public/assets/products/dbii_giatxa_4.jpg', '/public/assets/products/dbii_giatxa_5.jpg'],
    category: 'Combo Tiết Kiệm',
    tag: 'Up Sale',
    isHidden: false,
    description: 'Combo Up Sale đặc biệt.',
    soldCount: 200,
  },
  {
    id: 'no8',
    name: '6 túi giặt xả 1kg + 6 túi xả vải 1kg',
    price: 295000,
    originalPrice: 750000,
    image: '/public/assets/products/Combo_No08.jpg',
    images: ['/public/assets/products/dbii_giatxa.jpg', '/public/assets/products/dbii_xavai.jpg'],
    category: 'Combo Tiết Kiệm',
    tag: 'Up Sale',
    isHidden: false,
    description: 'Combo Up Sale đặc biệt.',
    soldCount: 85,
  },
  {
    id: 'no9',
    name: '1 túi giặt xả 1kg + 1 túi xả vải 1kg',
    price: 85000,
    originalPrice: 125000,
    image: '/public/assets/products/Combo_No09.jpg',
    images: ['/public/assets/products/dbii_giatxa.jpg', '/public/assets/products/dbii_xavai.jpg'],
    category: 'Combo Tiết Kiệm',
    tag: 'Up Sale',
    isHidden: false,
    description: 'Combo Up Sale đặc biệt.',
    soldCount: 600,
  },
  {
    id: 'no10',
    name: '1 thùng xả vải (tổng 6kg)',
    price: 175000,
    originalPrice: 390000,
    image: '/public/assets/products/Combo_No10.jpg',
    images: ['/public/assets/products/dbii_xavai.jpg', '/public/assets/products/dbii_xavai_2.jpg', '/public/assets/products/dbii_xavai_3.jpg', '/public/assets/products/dbii_xavai_4.jpg', '/public/assets/products/dbii_xavai_5.jpg'],
    category: 'Combo Tiết Kiệm',
    tag: 'Up Sale',
    isHidden: false,
    description: 'Combo Up Sale đặc biệt.',
    soldCount: 90,
  }
];

export const REVIEWS: Review[] = [
  {
    id: '1',
    user: 'Nguyễn Thu Hà',
    avatar: 'https://picsum.photos/100/100?random=220',
    rating: 5,
    comment: 'Cốc thả bồn cầu dùng rất thích, nước xanh và thơm mát, không còn mùi hôi khó chịu nữa.'
  },
  {
    id: '2',
    user: 'Trần Văn Minh',
    avatar: 'https://picsum.photos/100/100?random=221',
    rating: 5,
    comment: 'Tẩy đa năng siêu tốc làm sạch bếp rất nhanh, vết dầu mỡ lâu ngày cũng đi hết. Rất đáng tiền.'
  },
  {
    id: '3',
    user: 'Lê Thị Mai',
    avatar: 'https://picsum.photos/100/100?random=222',
    rating: 4,
    comment: 'Nước giặt xả thơm dịu, quần áo mềm mại, an toàn cho da tay. Sẽ ủng hộ shop dài dài.'
  }
];

export const CORE_VALUES: CoreValue[] = [
  {
    icon: 'FlaskConical',
    title: 'Công Nghệ Sinh Học',
    description: 'Sử dụng enzyme và nano bạc, an toàn tuyệt đối cho sức khỏe và môi trường.'
  },
  {
    icon: 'ShieldCheck',
    title: 'Công Nghệ Đức',
    description: 'Quy trình sản xuất tiên tiến, đạt chuẩn chất lượng Châu Âu.'
  },
  {
    icon: 'Leaf',
    title: 'Thành Phần Thiên Nhiên',
    description: 'Chiết xuất từ thiên nhiên, hương thơm dịu nhẹ, không hóa chất độc hại.'
  },
  {
    icon: 'Sparkles',
    title: 'Làm Sạch Vượt Trội',
    description: 'Đánh bay vết bẩn cứng đầu nhanh chóng, bảo vệ bề mặt vật dụng.'
  }
];

export const CATEGORIES = [
  "Tất cả",
  "Combo Tiết Kiệm",
  "Vệ sinh nhà cửa",
  "Giặt giũ",
  "Khử mùi"
];